#!/bin/bash

IMAGE_NAME="${IMAGE_NAME:-kamailio:master-alpine}"

set -x
docker rmi $IMAGE_NAME
docker rmi $IMAGE_NAME.debug
docker rmi $DOCKER_REPO:$SOURCE_BRANCH-alpine
docker rmi $DOCKER_REPO:$SOURCE_BRANCH-alpine.debug
exit 0