#!/bin/bash

IMAGE_NAME="${IMAGE_NAME:-kamailio:master-alpine}"

set -x
docker tag $IMAGE_NAME $DOCKER_REPO:$SOURCE_BRANCH-alpine \
    && docker tag $IMAGE_NAME.debug $DOCKER_REPO:$SOURCE_BRANCH-alpine.debug \
    && docker push $DOCKER_REPO:$SOURCE_BRANCH-alpine \
    && docker push $DOCKER_REPO:$SOURCE_BRANCH-alpine.debug

exit $?