---
name: dockerhub

on:
  push:
    branches:
      - '5.*'
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  pre-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          sudo apt-get install jq
          echo "matrix=$(bash get-all-dist.sh)" >> $GITHUB_OUTPUT
    outputs:
      dist: ${{ steps.set-matrix.outputs.matrix }}
  docker:
    needs: pre-docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist: ${{fromJson(needs.pre-docker.outputs.dist)}}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:${{ matrix.dist }}"
          # we need to build for arm64 first
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kamailio/kamailio:${{ github.ref_name }}-${{ matrix.dist }}
